# Custom Language File for Launcher Customizer

[ejs.app]
title = "SocialBlock Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur SocialBlock"
welcomeDescription = "Serveur Semi-RP PvP basé sur la création de Nation. Proliférez-là ou rejoignez-en une, devenez le plus puissant. Un sytème d'institution mondial tel que l'ONU est mis en place sur ce serveur. Pour plus d'informations, n'hésitez pas à nous contatcter ou à tester par vous même. Bon jeu à vous. "
welcomeDescCTA = "Encore quelques clics et vous pourrez vous connecter ."
